export { useExploreStore } from "./store";
export type { ReversalMode, ReversalPhase, DriftSample } from "./store";
export { useButterflyStore } from "./butterfly-store";
export type { DeltaEditMode, SeparationMetrics, SimSideState, EnergySnapshot } from "./butterfly-store";
export { ButterflySplit } from "./components/ButterflySplit";
export { SeparationAlert, DeltaPanel } from "./components/ButterflyUI";
export { Scene3D } from "./components/Scene3D";
export { TrailRenderer } from "./components/TrailRenderer";
export { TrailControls } from "./components/TrailControls";
export { TimeReversal } from "./components/TimeReversal";
export { TimeReversalTrajectoryOverlay, updateTrajectoryData, clearTrajectoryData } from "./components/TimeReversalTrajectory";
export { SonificationToggle } from "./components/SonificationToggle";
export { useSonification } from "./hooks/useSonification";
export type { UseSonificationAPI } from "./hooks/useSonification";
export { useChaosIndicator } from "./hooks/useChaosIndicator";
export type { ChaosIndicatorAPI } from "./hooks/useChaosIndicator";
export { useChaosUpdater } from "./hooks/useChaosUpdater";
export { ChaosIndicator } from "./components/ChaosIndicator";
export { useTrailBuffer } from "./hooks/useTrailBuffer";
export type { TrailPoint, TrailBufferAPI } from "./hooks/useTrailBuffer";
export { ExplorePage } from "./ExplorePage";
